name: iso
description: An isolates runner that handles bidirectionnal communication. Run
  some code in an isolate and communicate with it
author: synw <ansterj@gmail.com>
homepage: https://github.com/synw/iso
version: 0.4.0

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  extra_pedantic: ^1.2.0
  meta: ^1.2.4
  pedantic: ^1.9.2

dev_dependencies:
  test: ^1.15.7
  test_coverage: ^0.5.0
