name: iso
description: An isolates runner that handles bidirectionnal communication. Run some code in an isolate and communicate with it
author: synw <ansterj@gmail.com>
homepage: https://github.com/synw/iso
version: 0.2.2

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.1.7

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.3.0+1
